library(shiny)

slovar <- c("Belgium"="Belgija",
            "Bulgaria"="Bolgarija",
            "Czechia"="Češka",
            "Denmark"="Danska",
            "Germany "="Nemčija",
            "Estonia"="Estonija",
            "Ireland"="Irska",
            "Greece"="Grčija",
            "Spain"="Španija",
            "France"="Francija",
            "Croatia"="Hrvaška",
            "Italy"="Italija",
            "Cyprus"="Ciper",
            "Latvia"="Latvija",
            "Lithuania"="Litva",
            "Luxembourg"="Luksemburg",
            "Hungary"="Madžarska",
            "Malta"="Malta",
            "Netherlands"="Nizozemska",
            "Austria"="Avstrija",              
            "Poland"="Poljska",
            "Portugal"="Portugalska",
            "Romania"="Romunija",
            "Slovenia"="Slovenija",
            "Slovakia"="Slovaška",
            "Finland"="Finska",
            "Sweden"="Švedska",
            "United Kingdom"="Velika Britanija",        
            "Iceland"="Islandija",
            "Liechtenstein"="Lihtenštajn",
            "Norway"="Norveška",
            "Switzerland"="Švica",           
            "Montenegro"="Črna gora",
            "North Macedonia"="Severna Makedonija",
            "Albania"="Albanija",
            "Serbia"="Srbija",                
            "Turkey"="Turčija",
            "Andorra"="Andora",
            "Belarus"="Belorusija",
            "Bosnia and Herzegovina"="Bosna in Hercegovina",
            "Kosovo "="Kosovo",
            "Moldova"="Moldavija",
            "Russia"="Rusija",
            "San Marino"="San Marino",
            "Ukraine"="Ukrajina",
            "Armenia"="Armenija",
            "Azerbaijan"="Azerbajdžan",
            "Georgia"="Gruzija")

shinyUI(fluidPage(
  tabsetPanel(
    tabPanel("Slovenske regije",
             sidebarPanel(
               selectInput(inputId="regije",
                           label="Izberi leto",
                           choices=unique(regije$leto))),
             mainPanel(plotOutput("regije"))),
    tabPanel("Evropske države",
             sidebarPanel(
               selectInput(inputId="evropa",
                           label="Izberi državo",
                           choices=unique(slovar[EUpovrs$drzava]),
                           selected=unique(slovar[EUpovrs$drzava])[24])),
             mainPanel(plotOutput("evropa"))),
    tabPanel("Napoved za evropske države",
             sidebarPanel(
               selectInput(inputId="napoved",
                           label="Izberi državo",
                           choices=unique(slovar[EUpovrs$drzava]),
                           selected=unique(slovar[EUpovrs$drzava])[24])),
             mainPanel(plotOutput("napoved")))
)))
